FROM python:3.14-slim

#Configuración de zona horaria del contenedor
ENV TZ=Europe/Madrid
RUN apt-get update && apt-get install -y --no-install-recommends tzdata && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

CMD ["python", "main.py"]